<a href="https://colab.research.google.com/github/vinayk19/Assignment/blob/master/basic_RNN3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import torch.nn as nn
# from torch.autograd as Variable
from torch.autograd import Variable
import torch.autograd


In [2]:
h = [1,0,0,0]
e = [0,1,0,0]
l = [0,0,1,0]
o = [0,0,0,1]
h1 = torch.Tensor([[9,0,0,0]])

1. only one character as input and other 2 output will be there

In [3]:
cell = nn.RNN(input_size = 4, hidden_size =2 , batch_first = True) 

In [4]:
h1 = torch.Tensor([[h]])
h1.shape

torch.Size([1, 1, 4])

In [5]:
input = Variable(h1)
input.shape

torch.Size([1, 1, 4])

In [6]:
#h_0=(num_dir*num_layer, batch, hidden_size or output)
h_0 = Variable(torch.randn(1,1,2))
h_0.shape

torch.Size([1, 1, 2])

In [7]:
out, h_n = cell(input, h_0)
print("out shape", out.shape, "h_n shape", h_n.shape, "out value", out.data)

out shape torch.Size([1, 1, 2]) h_n shape torch.Size([1, 1, 2]) out value tensor([[[-0.5658,  0.0499]]])


2 .increasing sequence lenth to 5 (still 1 character in and 2 ch out)

In [8]:
input = Variable(torch.Tensor([[h,e,l,l,o]]))
input.shape #torch.Size([1, 5, 4]) batch, seq_len=5, input_size or dime =4

torch.Size([1, 5, 4])

In [9]:
#h_0=(num_dir*num_layer, batch, hidden_size or output =2) (same as old)
h_0 = Variable(torch.randn(1,1,2))
h_0.shape

torch.Size([1, 1, 2])

In [10]:
out, h_n = cell(input, h_0)
print("out shape", out.shape, "h_n shape", h_n.shape, "out value", out.data)

out shape torch.Size([1, 5, 2]) h_n shape torch.Size([1, 1, 2]) out value tensor([[[-0.8772,  0.8318],
         [-0.6335,  0.2881],
         [-0.7728, -0.0156],
         [-0.8138,  0.1857],
         [-0.7825,  0.2747]]])


3. increseing bacht size to 3 ( only input change)   

outout (2) and cell ramain same

In [11]:
input = Variable(torch.Tensor([[h,e,l,l,o], [e,l,l,o,h], [l,l,o,h,e] ]))
input.shape #torch.Size([1, 5, 4]) batch, seq_len=5, input_size or dime =4

torch.Size([3, 5, 4])

In [12]:
#h_0=(num_dir*num_layer, batch, hidden_size or output =2) (same as old)
h_0 = Variable(torch.randn(1,3,2))
h_0.shape

torch.Size([1, 3, 2])

In [13]:
out, h_n = cell(input, h_0)
print("out shape", out.shape, "h_n shape", h_n.shape, "out value", out.data)

out shape torch.Size([3, 5, 2]) h_n shape torch.Size([1, 3, 2]) out value tensor([[[-0.8800,  0.9310],
         [-0.6135,  0.2243],
         [-0.7807,  0.0289],
         [-0.8089,  0.1557],
         [-0.7862,  0.2937]],

        [[-0.4476, -0.0400],
         [-0.8087,  0.2132],
         [-0.7874,  0.0294],
         [-0.8011,  0.3715],
         [-0.7609,  0.4571]],

        [[-0.6621, -0.2585],
         [-0.8369,  0.3441],
         [-0.7619,  0.1705],
         [-0.7866,  0.5602],
         [-0.6811,  0.4513]]])


**4_1/** now predicting next character. inpuit at hihell and output as ihello (**only first character then get loss function here**

In [14]:
h = [1,0,0,0,0]
i = [0,1,0,0,0]
e = [0,0,1,0,0]
l = [0,0,0,1,0]
o = [0,0,0,0,1]
HH = [h,i, h, e, l, l]
yy = [i, h, e, l, l, o]

In [15]:
input = Variable(torch.Tensor([HH])) #torch.Size([1, 6, 5]) batch, seq_len=? , input_size or dime =?:  Note seq should be 6(as 6 character are going in) and input size (dim) = 5(1,0,0,0,0)

print(input.shape)

torch.Size([1, 6, 5])


In [16]:
h_o = Variable(torch.randn(1, 1, 5))#h_0=(num_dir*num_layer, batch, hidden_size or output =5) 
h_o.shape

torch.Size([1, 1, 5])

In [17]:
output_final = Variable(torch.Tensor([yy]))
output_final.shape

torch.Size([1, 6, 5])

In [18]:
cell = nn.RNN(input_size=5, hidden_size=5, batch_first=True)

In [19]:
out, h_0 = cell(input, h_o)
print("out shape", out.shape, "out type", out.type, "out value", out.data, "h_n shape", h_n.shape)

out shape torch.Size([1, 6, 5]) out type <built-in method type of Tensor object at 0x7fdc015085a0> out value tensor([[[ 0.8003,  0.3341, -0.7618,  0.7587, -0.3375],
         [-0.4493,  0.8603,  0.3869,  0.6478, -0.6592],
         [ 0.2645,  0.6602, -0.7471,  0.4480, -0.8522],
         [ 0.3637,  0.2855,  0.0618,  0.2982, -0.6919],
         [-0.2480,  0.3778, -0.3244,  0.2623, -0.8060],
         [-0.0494,  0.1734, -0.5455,  0.0930, -0.8828]]]) h_n shape torch.Size([1, 3, 2])


In [20]:
val, idx = out.max(1)
print("value ", val, "idx:", idx)

value  tensor([[ 0.8003,  0.8603,  0.3869,  0.7587, -0.3375]], grad_fn=<MaxBackward0>) idx: tensor([[0, 1, 1, 0, 0]])


In [21]:
print("idx data:", idx.data, "idx shape ", idx.data.shape)

idx data: tensor([[0, 1, 1, 0, 0]]) idx shape  torch.Size([1, 5])


In [22]:
print("idx data:", idx.data[0], "idx shape ", idx.data[0].shape)

idx data: tensor([0, 1, 1, 0, 0]) idx shape  torch.Size([5])


In [24]:
idx.data[0].numpy()

array([0, 1, 1, 0, 0])

In [25]:
idx2char=['h','i','e', 'l', 'o'] # 

In [26]:
idx2char[idx.data[0].numpy()[0]] # as idx data will take only scaler value so we need to convert it to int ie numpy

'h'

In [27]:
out2 = Variable(torch.LongTensor([h]))
out2.shape

torch.Size([1, 5])

input is batch, seq_len

In [28]:
criterion = nn.CrossEntropyLoss()
loss = 0 
# for i in range (6): #@ seq len =6 as 6 charecter are copmming in
loss += criterion(out, out2) # learning : 1. out2 needs a longTnesor. 2. it needs a scaler value not 2d etc (1,5)
print(loss)

tensor(1.9247, grad_fn=<AddBackward0>)


**4_2** now predicting next character. inpuit at hihell and output as ihello 
 **all first character one by one** then get loss function here 

In [29]:
idx2char=['h','i','e', 'l', 'o']
# h = [1,0,0,0,0]
# i = [0,1,0,0,0]
# e = [0,0,1,0,0]
# l = [0,0,0,1,0]
# o = [0,0,0,0,1]
one_hot_lookup = [[1,0,0,0,0], #0 
                  [0,1,0,0,0], #1
                  [0,0,1,0,0], #2
                  [0,0,0,1,0], #3
                  [0,0,0,0,1]] #4
x_data =[0, 1, 0, 2, 3, 3] # hihell

y_data =[1, 0, 2, 3, 3, 4] # ihello


In [30]:
y_data =[[1], [0], [2], [3], [3], [4]] # ihello
# y_data =[1, 0, 2, 3, 3, 4] # ihello

In [31]:
x_one_hot = [one_hot_lookup[x] for x in x_data]

In [32]:
x_one_hot

[[1, 0, 0, 0, 0],
 [0, 1, 0, 0, 0],
 [1, 0, 0, 0, 0],
 [0, 0, 1, 0, 0],
 [0, 0, 0, 1, 0],
 [0, 0, 0, 1, 0]]

In [33]:
inputs = Variable(torch.Tensor(x_one_hot))
labels = Variable(torch.LongTensor(y_data))


In [34]:
print(labels, inputs)

tensor([[1],
        [0],
        [2],
        [3],
        [3],
        [4]]) tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 1., 0.]])


In [35]:
#  inputs = Variable(torch.Tensor(x))

In [36]:
num_classes =5 # non RNN parameter twll how many classes here
input_size= 5 # no if input dimenitons
seq_len = 1 # as 1 characterr are going in at once for 6 times
hiddenO = 5 # output dimention
batch =  1 
num_dir =1
num_layer =1

In [37]:
class net(nn.Module):
  def __init__(self):
    super(net, self).__init__()

    self.input_size = 5
    self.hiddenO = 5
    self.seq_len = 1
    self.batch = 1
    self.num_classes = 5
    self.num_direction = 1
    self.num_layer =1

    self.cell = nn.RNN(input_size = self.input_size, hidden_size=self.hiddenO, batch_first=True)

  def forward(self, input, h_O):
    
    input = input.view(self.batch, self.seq_len, self.input_size)

    out, h_n = self.cell(input, h_O)
    out = out.view(-1, self.num_classes) # to flatten to get the classes

    return out, h_n
  
  def init_hidden(self):
    return Variable(torch.zeros(self.num_direction*self.num_layer, self.batch, self.hiddenO))

In [38]:
model = net()

In [39]:
labels[0].shape
inputs[0]

tensor([1., 0., 0., 0., 0.])

In [40]:
# criterion = nn.CrossEntropyLoss()
# optimizer = torch.optim.Adam(model.parameters(), lr = .1)

Training 

In [54]:
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr = .1)

for epoch in range (50):
  loss = 0
  hidden = model.init_hidden() # learning
  # sys.stdout.write("Predictedd string: ")
  result_new = ""
  for input, label in zip(inputs, labels): #learning # zip
    # print("input_size", input.size(), "lables", label.size())
    out, hidden = model(input, hidden)
    val, idx = out.max(1) # learning it provides max values in each column and its index
    # sys.stdout.write(idx2char[idx.data[0]]) # learning try to predict out output
    # print("idx data,", idx.data[0])
    loss += criterion(out, label)
    idx = idx.data.numpy()
    result_str = [idx2char[c][0] for c in idx]
    # print("result_str_size", result_str, "result_str type", type(result_str))
    # result_new = result_strp.join(result_str)
    # result_new = result_strp + result_str[0]
    result_new = result_new + result_str[0]
    # result_new = result_new.join(result_str[0])
    # print("result_new", result_new)
    # print("result_strp", result_strp, '\n')

    
  print ("result str:", result_new)
  

  loss.backward()
  optimizer.step()
  print("Epoch: %d, loss: %1.3f" % (epoch +1, loss.data) )

result str: oooooo
Epoch: 1, loss: 7.814
result str: oooooo
Epoch: 2, loss: 7.814
result str: oooooo
Epoch: 3, loss: 7.814
result str: oooooo
Epoch: 4, loss: 7.814
result str: oooooo
Epoch: 5, loss: 7.814
result str: oooooo
Epoch: 6, loss: 7.814
result str: oooooo
Epoch: 7, loss: 7.814
result str: oooooo
Epoch: 8, loss: 7.814
result str: oooooo
Epoch: 9, loss: 7.814
result str: oooooo
Epoch: 10, loss: 7.814
result str: oooooo
Epoch: 11, loss: 7.814
result str: oooooo
Epoch: 12, loss: 7.814
result str: oooooo
Epoch: 13, loss: 7.814
result str: oooooo
Epoch: 14, loss: 7.814
result str: oooooo
Epoch: 15, loss: 7.814
result str: oooooo
Epoch: 16, loss: 7.814
result str: oooooo
Epoch: 17, loss: 7.814
result str: oooooo
Epoch: 18, loss: 7.814
result str: oooooo
Epoch: 19, loss: 7.814
result str: oooooo
Epoch: 20, loss: 7.814
result str: oooooo
Epoch: 21, loss: 7.814
result str: oooooo
Epoch: 22, loss: 7.814
result str: oooooo
Epoch: 23, loss: 7.814
result str: oooooo
Epoch: 24, loss: 7.814
r