<a href="https://colab.research.google.com/github/vinayk19/Assignment/blob/master/CNN_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch
import torchvision

# **Conv2d 1d** Example 1d\
torch.nn.Conv2d(in_channels, out_channels, kernel_size, stride=1, padding=0, dilation=1, groups=1, bias=True, padding_mode='zeros')

So the in_channels in the beginning is 3 for images with 3 channels (colored images). For images black and white it should be 1. Some satellite images should have 4.

The out_channels is what convolution will produce so these are the **number of filters.**


In [2]:
 c = torch.nn.Conv2d(1,3, stride = 1, kernel_size = (4,5))
 print(c.weight.shape)
 print(c.weight)

torch.Size([3, 1, 4, 5])
Parameter containing:
tensor([[[[ 0.2182, -0.1086, -0.1316, -0.0397,  0.1063],
          [-0.1451, -0.1484,  0.1554, -0.0186,  0.0261],
          [-0.0700,  0.1159, -0.1921,  0.2216,  0.0835],
          [-0.1352, -0.0753, -0.1653, -0.1486, -0.0995]]],


        [[[-0.1097, -0.1166,  0.1925, -0.1203,  0.0226],
          [ 0.0565,  0.0950,  0.1264,  0.0300,  0.0145],
          [-0.0995,  0.1317, -0.0858, -0.1637, -0.1270],
          [-0.0653, -0.1054,  0.0852, -0.0463,  0.1963]]],


        [[[ 0.1061,  0.0150,  0.1275,  0.1682, -0.2122],
          [-0.0175,  0.0910, -0.2110,  0.1512,  0.0553],
          [-0.0935,  0.1005, -0.0046, -0.1503,  0.0584],
          [-0.1342, -0.2112, -0.1114, -0.1706, -0.1445]]]], requires_grad=True)


In [3]:
 c = torch.nn.Conv2d(1,5, stride = 1, kernel_size = (4,5))
 print(c.weight.shape)
 print(c.weight)

torch.Size([5, 1, 4, 5])
Parameter containing:
tensor([[[[ 1.9351e-01, -1.8174e-01, -4.7789e-02, -1.4406e-01, -1.7552e-02],
          [ 1.7000e-01, -1.3898e-01,  4.8733e-03,  2.0059e-01, -7.2878e-02],
          [ 1.2508e-02,  1.9801e-01, -3.6867e-02,  1.2918e-01, -1.5179e-01],
          [-1.3442e-01, -1.2397e-01,  8.5477e-02,  2.1917e-01, -1.1915e-01]]],


        [[[-1.0836e-01, -1.0360e-01,  1.0292e-01, -2.2175e-01,  9.9093e-02],
          [ 1.1426e-01, -1.8283e-01,  5.9316e-02, -5.0230e-02,  4.0918e-02],
          [ 1.7779e-01, -7.1195e-02,  2.0888e-01, -1.3882e-02,  1.4721e-01],
          [ 9.9359e-02, -2.1198e-01, -1.4503e-02,  2.8081e-02,  1.7089e-01]]],


        [[[ 1.4866e-01, -1.3066e-01,  8.0951e-03, -1.7019e-01, -1.2110e-02],
          [ 2.1631e-01, -3.6557e-02, -9.3217e-02,  1.9946e-01, -3.9478e-02],
          [ 1.2499e-01, -1.4847e-01, -4.2959e-02, -1.3678e-01, -1.8746e-01],
          [-1.9732e-01, -3.9062e-03,  8.9821e-02, -8.7414e-02, -1.1592e-01]]],


        [[[ 1.426

2 in channel and 3 filter
**Note : no of channel at input and output remains same ie 2 althogh changed filter**

In [13]:
c = torch.nn.Conv2d(2,3, stride = 1, kernel_size = (4,5)) #( 3 output fileter)
print(c.type)
print(c.weight.shape)
print(c.weight)

<bound method Module.type of Conv2d(2, 3, kernel_size=(4, 5), stride=(1, 1))>
torch.Size([3, 2, 4, 5])
Parameter containing:
tensor([[[[-0.1008,  0.0610, -0.0912, -0.1417,  0.1253],
          [ 0.0815, -0.0631, -0.1209,  0.0789, -0.0761],
          [ 0.1364, -0.0093,  0.1035,  0.0808,  0.1108],
          [ 0.1236, -0.0196, -0.0164, -0.0367, -0.1192]],

         [[-0.0820,  0.0768, -0.0780,  0.0970,  0.0208],
          [-0.1225,  0.1247,  0.0534,  0.1563,  0.0732],
          [-0.0702, -0.1250, -0.1464, -0.0714,  0.1119],
          [ 0.0260, -0.0633, -0.0542,  0.0363, -0.0927]]],


        [[[ 0.0434,  0.1048,  0.0040, -0.1115,  0.1095],
          [ 0.1367,  0.0211,  0.0593,  0.1111,  0.0292],
          [-0.0403, -0.1147, -0.1275, -0.1088, -0.0635],
          [ 0.0683,  0.1155, -0.1024, -0.0580, -0.0522]],

         [[ 0.0749, -0.0551, -0.0264, -0.0570,  0.0011],
          [-0.0637,  0.0669, -0.1523,  0.1468, -0.0625],
          [-0.0571,  0.0146,  0.0365,  0.1455,  0.0589],
          [-

applying con2d in **Input data**

In [38]:
bs=4
x = torch.randn(bs, 3, 28, 28)
c = torch.nn.Conv2d(3,2,kernel_size=5,stride=1,padding=2) # in channel =3 seen same 3 at x(input) which is channel. ip has image of 28*28 with 3 cahnnel 
print("conv2d type ", c.type)
print("conv2d shape ",c.weight.shape)
print("conv2d weight ",c.weight)
out = c(x)
print("out type ", out.type)
# print(out.weight.shape)
# print(out.weight)
print("out shape ",out.shape)
print(out.nelement()) #125440 number of activations

conv2d type  <bound method Module.type of Conv2d(3, 2, kernel_size=(5, 5), stride=(1, 1), padding=(2, 2))>
conv2d shape  torch.Size([2, 3, 5, 5])
conv2d weight  Parameter containing:
tensor([[[[ 0.0116,  0.0465, -0.0911, -0.0530, -0.1102],
          [ 0.0666, -0.0053,  0.0467,  0.0217, -0.0732],
          [ 0.0378,  0.0937,  0.0272,  0.0680, -0.0773],
          [-0.0503, -0.0512,  0.1082,  0.0934, -0.0902],
          [ 0.0662,  0.1128,  0.0461, -0.0746, -0.0960]],

         [[-0.0118,  0.1104, -0.0027,  0.0875, -0.0088],
          [ 0.0590, -0.1059,  0.0965,  0.0942, -0.0044],
          [ 0.0565,  0.0995,  0.0743,  0.0984,  0.0183],
          [ 0.0594, -0.0735, -0.0311,  0.0824, -0.1020],
          [-0.0374,  0.0173,  0.0786,  0.0959,  0.0122]],

         [[-0.0433,  0.0125,  0.1094, -0.1057, -0.0302],
          [ 0.0812, -0.1005,  0.0622,  0.0281,  0.0655],
          [ 0.0076, -0.0006,  0.0321,  0.0445, -0.0756],
          [ 0.0491,  0.0275,  0.0194,  0.0539,  0.0625],
          [-0.0

**Max POOL**
MaxPool2d , MaxPool1d etc

torch.nn.MaxPool2d(kernel_size, stride=None, padding=0, dilation=1, return_indices=False, ceil_mode=False)

In [32]:
m = torch.nn.MaxPool2d(kernel_size=2)
print("conv2d type ", m.type)

conv2d type  <bound method Module.type of MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)>


Applying MaxPool2d

In [0]:
out_MP = m(out)
print("input to MP ", out.shape)
print("out_MP type ", out_MP.type)
print("output shape of of maxpool is ", out_MP.shape)
print(out_MP.nelement()) #  number of activations
out_MP

# Applying Activation Function ReLU

In [0]:
z= torch.nn.ReLU()  # need to check its type shape and values

In [0]:
out_act = z(out_MP) # applied activation but need to check its type shape and values

In [0]:
out_flattening = out_act.view(x, -1) #flattening as input x


need to flatten values
apply funny linear layer (nn. linear)
apply softmax above that