<a href="https://colab.research.google.com/github/vinayk19/Assignment/blob/master/RNN_basic2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

https://towardsdatascience.com/pytorch-basics-how-to-train-your-neural-net-intro-to-rnn-cb6ebc594677

In [0]:
import numpy as np

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader

input 1:20 , Batch Size = 4
Sequence Length = 5
Input Size = 1 (Since, only one dimension)

In [3]:
data = torch.Tensor([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])
# data = torch.Tensor([range(1,21)])
print("Data: ", data.shape, "\n\n", data)

Data:  torch.Size([20]) 

 tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
        15., 16., 17., 18., 19., 20.])


Vanilla RNN 

1. define inputs parameter: input and h0

Input


```
# This is formatted as code
```


  seq_length = 5 # length if longest sequence

  batch= 4 # no of batches

  input_size = 1 # no of imput dimention

   num_ layer =1 no of stacked enn layer

h0

2. output parameter

In [0]:
# Imputs = input & ho
#input
seq_length = 5 # length if longest sequence 
batch= 4 # no of batches
input_size = 1 # no of imput dimention
# using batch_first [b s i]
#h0
num_layer =1 # nos of stacked rnn layers
num_direction =1 # 2 for bi
#batch = 4 #same as input $$$$
hidden_size_h0 = input_size #Note

In [0]:
# Outputs = output, hn
# Output
seq_lengthO = 5 # note length if longest sequence 
batchO= 4 # no of batches
# num_directionO = 1 ? # no of input dimention
hidden_sizeO = 2 

In [0]:
# Initialize the RNN. ? what is function
rnn = nn.RNN(input_size=input_size, hidden_size=hidden_sizeO, num_layers= num_layer, batch_first=True)
# input size : (batch, seq_len, input_size)
inputs = data.view(batch, seq_length, input_size)
h_o = torch.randn(1,4,2) # ho:  (num_layers * num_directions, batch, hidden_size)
# out shape = (batch, seq_len, num_directions * hidden_size)
# h_n shape  = (num_layers * num_directions, batch, hidden_size)
out, h_n = rnn(inputs, h_o) # can ignore h_0 as well

In [7]:
print('Input: ', inputs.shape, '\n', inputs)# input shape = [4, 5, 1]
print('\nOutput: ', out.shape, '\n', out)# out shape = [4, 5, 2]
print('\nHidden: ', h_n.shape, '\n', h_n)# h_n shape = [1, 4, 2]

Input:  torch.Size([4, 5, 1]) 
 tensor([[[ 1.],
         [ 2.],
         [ 3.],
         [ 4.],
         [ 5.]],

        [[ 6.],
         [ 7.],
         [ 8.],
         [ 9.],
         [10.]],

        [[11.],
         [12.],
         [13.],
         [14.],
         [15.]],

        [[16.],
         [17.],
         [18.],
         [19.],
         [20.]]])

Output:  torch.Size([4, 5, 2]) 
 tensor([[[ 0.8822,  0.9647],
         [-0.3763,  0.8608],
         [ 0.2885,  0.8774],
         [ 0.2583,  0.9588],
         [ 0.4025,  0.9779]],

        [[ 0.6028,  0.9961],
         [ 0.5993,  0.9958],
         [ 0.7144,  0.9980],
         [ 0.7850,  0.9991],
         [ 0.8444,  0.9996]],

        [[ 0.9899,  0.9999],
         [ 0.9173,  0.9999],
         [ 0.9467,  1.0000],
         [ 0.9634,  1.0000],
         [ 0.9752,  1.0000]],

        [[ 0.9975,  1.0000],
         [ 0.9886,  1.0000],
         [ 0.9924,  1.0000],
         [ 0.9949,  1.0000],
         [ 0.9966,  1.0000]]], grad_fn=<Transpose

Stacket RNN 3 layers stacked
num_layer =3

In [0]:
num_layer= 3
rnn = nn.RNN(input_size, hidden_sizeO, num_layer, batch_first=True)

In [9]:
input = data.view(batch,seq_length,input_size)
h_o = torch.zeros(num_layer*num_direction, batch, hidden_sizeO)
print('Input: ', inputs.shape, 'h_o', h_o.shape, )

Input:  torch.Size([4, 5, 1]) h_o torch.Size([3, 4, 2])


In [10]:
# out, h_n = rnn(input, h_o)
out, h_n = rnn(input)
print('out: ', out.shape, 'h_n', h_n.shape )

out:  torch.Size([4, 5, 2]) h_n torch.Size([3, 4, 2])


**Bitidection RNN**: paramerter (bidirection = true), h_0 or h_n: num_direection =2

(if not made num_direction at h_0 then it will come automatically at h_n)  


In [11]:
num_direction =2
num_layer =1
rnn = nn.RNN(input_size, hidden_sizeO, num_layer, bidirectional= True, batch_first=True)
input = data.view(batch, seq_length, input_size) #input size : (batch, seq_len, input_size)
h_o = torch.zeros(num_layer*num_direction, batch, hidden_sizeO)#ho:  (num_layers * num_directions, batch, hidden_size)
print('Input: ', inputs.shape, 'h_o', h_o.shape, )

Input:  torch.Size([4, 5, 1]) h_o torch.Size([2, 4, 2])


In [12]:
# out, h_n = rnn(input, h_o)
out, h_n = rnn(input)
print('out: ', out.shape, 'h_n', h_n.shape )

out:  torch.Size([4, 5, 4]) h_n torch.Size([2, 4, 2])


In [0]:
print('Input: ', inputs.shape, '\n', inputs)# input shape = [4, 5, 1]
print('\nOutput: ', out.shape, '\n', out)# out shape = [4, 5, 2]
print('\nHidden: ', h_n.shape, '\n', h_n)# h_n shape = [1, 4, 2]

**BIRNN seperated out (not h_n**

Let’s **reshape the BiRNN output** to separate out** forward and backward values **using    :

 out.view(batch, seq_len, num_directions, hidden_size).

In [20]:
out_reshaped = out.view(batch, seq_length, num_direction, hidden_sizeO)
print("Shape of the output after directions are separated: ", out_reshaped.shape)

Shape of the output after directions are separated:  torch.Size([4, 5, 2, 2])


In [0]:
out_forward = out_reshaped[:, :, 0, :]
out_backward = out_reshaped[:, :, 1, :]
print("Forward output: ", out_forward.shape, "\n", out_forward)
print("\n\nBackward output: ", out_backward.shape, "\n", out_backward)

In [0]:
**BIRNN seperated h_n**

Let’s **reshape the BiRNN h_n** to separate out** forward and backward values **using    :

h_n.view(num_layer, num_direction, batch, hidden_sizeO)

In [29]:
h_n_reshaped = h_n.view(num_layer, num_direction, batch, hidden_sizeO)
print("Shape of the output after directions are separated: ", h_n_reshaped.shape, '\n', h_n_reshaped)

Shape of the output after directions are separated:  torch.Size([1, 2, 4, 2]) 
 tensor([[[[ 0.6057,  0.2082],
          [ 0.4775,  0.1011],
          [ 0.3182, -0.0119],
          [ 0.1338, -0.1272]],

         [[ 0.7576, -0.0838],
          [ 0.9072, -0.9966],
          [ 0.9680, -1.0000],
          [ 0.9893, -1.0000]]]], grad_fn=<ViewBackward>)


In [28]:
h_n_forward = h_n_reshaped[:, 0, :, :]
h_n_backward = h_n_reshaped[:, 1, :, :]
print("Forward output: ", h_n_forward.shape, "\n", h_n_forward)
print("\n\nBackward output: ", h_n_backward.shape, "\n", h_n_backward)

Forward output:  torch.Size([1, 4, 2]) 
 tensor([[[ 0.6057,  0.2082],
         [ 0.4775,  0.1011],
         [ 0.3182, -0.0119],
         [ 0.1338, -0.1272]]], grad_fn=<SliceBackward>)


Backward output:  torch.Size([1, 4, 2]) 
 tensor([[[ 0.7576, -0.0838],
         [ 0.9072, -0.9966],
         [ 0.9680, -1.0000],
         [ 0.9893, -1.0000]]], grad_fn=<SliceBackward>)
